-- AlterTable
ALTER TABLE "services" ALTER COLUMN "price" DROP DEFAULT,
ALTER COLUMN "unit" DROP DEFAULT,
ALTER COLUMN "turnaround" DROP DEFAULT,
ALTER COLUMN "category" DROP DEFAULT,
ALTER COLUMN "features" DROP DEFAULT;
