-- Add wallet quick slots configuration
INSERT INTO "configurations" ("key", "value", "description", "category", "isActive", "createdAt", "updatedAt") VALUES
('wallet_quick_slots_enabled', 'true', 'Enable/disable wallet quick slots feature', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_1_amount', '5', 'Quick slot 1 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_1_reward', '0.5', 'Reward for quick slot 1 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_1_enabled', 'true', 'Enable/disable quick slot 1', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_2_amount', '10', 'Quick slot 2 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_2_reward', '1', 'Reward for quick slot 2 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_2_enabled', 'true', 'Enable/disable quick slot 2', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_3_amount', '20', 'Quick slot 3 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_3_reward', '2.5', 'Reward for quick slot 3 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_3_enabled', 'true', 'Enable/disable quick slot 3', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_4_amount', '50', 'Quick slot 4 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_4_reward', '7', 'Reward for quick slot 4 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_4_enabled', 'true', 'Enable/disable quick slot 4', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_5_amount', '100', 'Quick slot 5 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_5_reward', '15', 'Reward for quick slot 5 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_5_enabled', 'true', 'Enable/disable quick slot 5', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_6_amount', '25', 'Quick slot 6 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_6_reward', '3', 'Reward for quick slot 6 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_6_enabled', 'false', 'Enable/disable quick slot 6', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_7_amount', '75', 'Quick slot 7 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_7_reward', '10', 'Reward for quick slot 7 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_7_enabled', 'false', 'Enable/disable quick slot 7', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_8_amount', '150', 'Quick slot 8 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_8_reward', '25', 'Reward for quick slot 8 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_8_enabled', 'false', 'Enable/disable quick slot 8', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_9_amount', '200', 'Quick slot 9 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_9_reward', '35', 'Reward for quick slot 9 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_9_enabled', 'false', 'Enable/disable quick slot 9', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_10_amount', '500', 'Quick slot 10 amount (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_10_reward', '100', 'Reward for quick slot 10 (in BHD)', 'wallet_quick_slots', true, NOW(), NOW()),
('wallet_quick_slot_10_enabled', 'false', 'Enable/disable quick slot 10', 'wallet_quick_slots', true, NOW(), NOW());
